### ISSUE TITLE
IMPORTANT!! Double Spend

### ISSUE THREAD

**Issue by dezzyboy** [carsenk/denariusnodewallet#10]
you need to fix your code as once private key is imported to a desktop wallet there it then allows user to spend the amount from the web wallet and also from the desktop wallet as long as there is a full node running on the server with a valid balance users account uses that balance to send

**Comment by metaspartan** [comment]
Closing this issue as it isn't one. The web wallet development stopped awhile ago, the web wallet requires a node running that you own the private keys to, I believe I had it setup to display private keys to addresses you owned with the accounting system. There is no double spend issue here though or any issue at all
