### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by rupaya-project** [carsenk/denariusnodewallet#3]
Hi,

I've just forked your project to adapt it to our currency.

I was wondering if staking has been implemented ?

Regards

**Comment by metaspartan** [comment]
Staking is currently not implemented. It is recommended to run your coind with staking=0 and enableaccounts=0

Also fees still need reworking to work better with the move cmd, I will hopefully add this in sometime in the coming weeks.

**Comment by rupaya-project** [comment]
I've got couple of more questions don't want to spam GitHub, would it possible to reach you on twitter ?

**Comment by metaspartan** [comment]
Yea my Twitter is https://twitter.com/carsenjk and Denarius Twitter is https://twitter.com/denariuscoin
